#!/usr/bin/env bash
# Key management

chain=$(which envchain)

usage(){
  app_name=$(basename $0)

  echo ""
  echo "Usage:"
  echo -e "\t$app_name -l | -c | -g | -h"
  echo ""
  echo "Options:"
  echo -e "\t-l \t Prompt for AWS credentials"
  echo -e "\t-c \t Show AWS credentials"
  echo -e "\t-g \t Show gpg secure keys" 
  echo -e "\t-h \t Show help screen" 
  echo ""
}

# Load envchain
load_env(){
  $chain --set --noecho aws AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION
}

check_env(){
  envchain aws env | grep AWS_
}

check_gpg(){
  gpg --list-secret-keys

}

case $1 in
-l)
 	load_env
	;;
-c)
	check_env
	;;
-g)
	check_gpg
	;;
*)
	usage
	;;
esac


