#!/bin/sh

backcolor="#CCFFCC"
backcolor2="#CCCCFF"
domain="$1"
ip_address=$(dig +short -ta $domain)

echo "<h1>IP Owner Report</h1>"

echo "<table border=0 cellpadding=4 cellspacing=4>"
echo "<tr bgcolor=$backcolor>"
	echo "<td>IP Address</td>"
	echo "<td>$ip_address</td>"
echo "</tr>"
echo "<tr bgcolor=$backcolor2>"
        echo "<td>Reverse IP Address - PTR record</td>"
        echo "<td>$(dig +short -x $ip_address)</td>"
echo "</tr>"
echo "<tr bgcolor=$backcolor>"
	echo "<td>IP Owner Information</td>"
	echo "<td>$(whois -h whois.cyberabuse.org -p 43 $domain| sed '/\[/d' | sed '/\%/d'| sed '/^$/d')</td>"
echo "</tr>"

echo "<tr bgcolor=$backcolor2>"
	echo "<td></td>"
	echo "<td>$(whois -h whois.radb.net $domain | sed '/\[/d')</td>"
echo "</tr>"

echo "<tr bgcolor=$backcolor>"
	echo "<td>ASN Information</td>"
	echo "<td>$(whois -h v4.whois.cymru.com " -n -b $ip_address"  | sed '/\[/d'| sed '/\#/d')</td>"
echo "</tr>"
echo "<tr bgcolor=$backcolor2>"
	echo "<td>ASN Peer</td>"
	echo "<td>$(whois -h v4-peer.whois.cymru.com " -n -f $ip_address" | sed '/\[/d'| sed '/\#/d')</td>"
echo "</tr>"
echo "</table>"

echo "<table>"
echo "<tr>"
        echo "<td align=left>"
                echo "<form action=/reports/ip_report.php method=post>"
                echo "IP Address <input type=text name=ip> <input type=submit value=check>"
                echo "<input type=hidden name=tool_option value=ipreport>"
                echo "</form>"
        echo "</td>"
echo "</tr>"
echo "</table>"
